"""
N2NHU World Generator - INI Writer
====================================
Writes WorldConfig to six INI files using configparser —
the same library the game engine uses to read them.

Write with the same tool the engine reads with.
If configparser can write it, configparser can read it.
That is the round-trip guarantee.

N2NHU Labs for Applied Artificial Intelligence
"""

import configparser
import os
import re
from typing import Dict
from world_model import WorldConfig


def _escape_percent(value: str) -> str:
    """Escape bare % for ConfigParser interpolation safety."""
    return re.sub(r'(?<!%)%(?!%)', '%%', str(value))


class INIWriter:
    """
    Writes all six INI files from a WorldConfig.
    Every value is percent-escaped before writing.
    Section naming invariants (SD1, etc) are enforced here.
    """

    def write_all(self, world: WorldConfig, output_dir: str) -> Dict[str, str]:
        """
        Write all 6 INI files to output_dir.
        Returns dict of {filename: full_path}.
        """
        os.makedirs(output_dir, exist_ok=True)

        written = {}
        written['rooms.ini']           = self._write_rooms(world, output_dir)
        written['objects.ini']         = self._write_objects(world, output_dir)
        written['sprites.ini']         = self._write_sprites(world, output_dir)
        written['transformations.ini'] = self._write_transformations(world, output_dir)
        written['combat.ini']          = self._write_combat(world, output_dir)
        written['stablediffusion.ini'] = self._write_sd(world, output_dir)

        return written

    def _new_config(self) -> configparser.ConfigParser:
        """Create a fresh ConfigParser with interpolation DISABLED."""
        # Disable interpolation to allow literal % in values
        return configparser.RawConfigParser()

    def _set_section(self, config: configparser.RawConfigParser,
                     section: str, data: Dict[str, str]):
        """Add a section with escaped values."""
        config.add_section(section)
        for key, value in data.items():
            config.set(section, key, _escape_percent(str(value)))

    def _write_config(self, config: configparser.RawConfigParser,
                      path: str, header: str = ''):
        with open(path, 'w', encoding='utf-8') as f:
            if header:
                f.write(header + '\n')
            config.write(f)

    # ── rooms.ini ────────────────────────────────────────────
    def _write_rooms(self, world: WorldConfig, output_dir: str) -> str:
        config = self._new_config()
        for room_id, room in world.rooms.items():
            self._set_section(config, room_id, room.to_ini_section())
        path = os.path.join(output_dir, 'rooms.ini')
        self._write_config(config, path,
            f'# Room Definitions - {world.world_name}\n'
            f'# Generated by N2NHU World Generator\n'
            f'# Rooms: {len(world.rooms)}\n')
        return path

    # ── objects.ini ──────────────────────────────────────────
    def _write_objects(self, world: WorldConfig, output_dir: str) -> str:
        config = self._new_config()
        for obj_id, obj in world.objects.items():
            self._set_section(config, obj_id, obj.to_ini_section())
        path = os.path.join(output_dir, 'objects.ini')
        self._write_config(config, path,
            f'# Object Definitions - {world.world_name}\n'
            f'# Generated by N2NHU World Generator\n'
            f'# Objects: {len(world.objects)}\n')
        return path

    # ── sprites.ini ──────────────────────────────────────────
    def _write_sprites(self, world: WorldConfig, output_dir: str) -> str:
        config = self._new_config()
        for sprite_id, sprite in world.sprites.items():
            self._set_section(config, sprite_id, sprite.to_ini_section())
        path = os.path.join(output_dir, 'sprites.ini')
        self._write_config(config, path,
            f'# Sprite Definitions - {world.world_name}\n'
            f'# Generated by N2NHU World Generator\n'
            f'# Sprites: {len(world.sprites)}\n')
        return path

    # ── transformations.ini ──────────────────────────────────
    def _write_transformations(self, world: WorldConfig, output_dir: str) -> str:
        config = self._new_config()
        for t_id, t in world.transformations.items():
            self._set_section(config, t_id, t.to_ini_section())
        path = os.path.join(output_dir, 'transformations.ini')
        self._write_config(config, path,
            f'# Transformation Matrices - {world.world_name}\n'
            f'# Generated by N2NHU World Generator\n'
            f'# Transforms: {len(world.transformations)}\n')
        return path

    # ── combat.ini ───────────────────────────────────────────
    def _write_combat(self, world: WorldConfig, output_dir: str) -> str:
        config = self._new_config()
        # Use start room as respawn if not explicitly set
        respawn = world.combat.respawn_location or world.start_room or ''
        for section, data in world.combat.to_ini_sections(respawn).items():
            self._set_section(config, section, data)
        path = os.path.join(output_dir, 'combat.ini')
        self._write_config(config, path,
            f'# Combat Matrix - {world.world_name}\n'
            f'# Generated by N2NHU World Generator\n')
        return path

    # ── stablediffusion.ini ──────────────────────────────────
    def _write_sd(self, world: WorldConfig, output_dir: str) -> str:
        config = self._new_config()
        for section, data in world.sd_config.to_ini_sections().items():
            self._set_section(config, section, data)
        path = os.path.join(output_dir, 'stablediffusion.ini')
        self._write_config(config, path,
            f'# Stable Diffusion Configuration - {world.world_name}\n'
            f'# Generated by N2NHU World Generator\n'
            f'# CRITICAL: SD server sections MUST start with "SD"\n'
            f'# CRITICAL: host and port are SEPARATE keys\n')
        return path
